import CookieConsentScript from "../../components/CookieConsent";

export const metadata = {
  title: "Deutscher Pavillon",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <CookieConsentScript />
      <body>{children}</body>
    </html>
  );
}
